# @package _group_

path: /ibex/ai/home/shenx/video/data/${dataset.name}
path_for_slurm_job: ${env.datasets_dir}/${dataset.name}
name: coinrun_${dataset.resolution}
resolution: 256
fps: 30
motion_map: false
mask: false
metrics: ["fvd2048_16f"]
augpipe: bgc_noro
